linters:
  # Allow /* */ style comments
  Comment:
    enabled: false
  # Allow tab indent
  Indentation:
    enabled: true
    character: tab
    width: 1
  # Allow empty lines between { } for brevity
  EmptyLineBetweenBlocks:
    enabled: false
  # Increase nesting depth
  NestingDepth:
    enabled: true
    max_depth: 5
  # Allow space after property: for alignment
  SpaceAfterPropertyColon:
    enabled: false
  # Allow color keywords and literals because they're legit
  ColorKeyword:
    enabled: false
  ColorVariable:
    enabled: false
  # Allow !important as we use it to override javascript responsively
  ImportantRule:
    enabled: false
  # Property sort order - recess (twitter / bootstrap)
  PropertySortOrder:
    order: recess
